theme: jekyll-theme-slate

title: Lumorian's Website

<style>
    img[alt="github"]{
        width:70px;
    }
    img[alt="bilibili"]{
        width:70px;
    }
    img[alt="discord"]{
        width:70px;
    }
    img[alt="telegram"]{
        width:70px;
    }
</style>
