theme: jekyll-theme-slate

title: Lumorian's Website

<style>
    #txt{
        font-size:1.5rem;
    }
    img[alt="github"]{
        width:70px;
    }
    img[alt="bilibili"]{
        width:70px;
    }
    img[alt="discord"]{
        width:70px;
    }
    img[alt="telegram"]{
        width:70px;
    }
